- name: provision stack
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "vars/cf_vars.yaml"
  tasks:
  - name: launch the opennms minion lab stack
    cloudformation:
      stack_name: "opennms-minion-lab"
      state: "present"
      region: "us-east-1"
      disable_rollback: true
      template: "opennms.json"
      template_parameters:
        KeyName: "{{ KeyName }}"
        EC2InstanceType: "{{ EC2InstanceType }}"
        MinionCount: "{{ MinionCount }}"
        KafkaCount: "{{ KafkaCount }}"
        ElasticCount: "{{ ElasticCount }}"
      tags:
        Owner: "jesse"
        Env: "DEV"
    register: stack
    tags:
     - provision
  - name: show stack outputs
    debug:
      msg: "Lab stack outputs are {{stack.stack_outputs}}"
    tags:
     - provision
  - name: destroy stack
    cloudformation:
      stack_name: "opennms-minion-lab"
      state: "absent"
      region: "us-east-1"
    tags:
     - destroy

- hosts: tag_aws_cloudformation_stack_name_opennms_minion_lab
  roles:
    - common

- hosts: tag_MinionLabInstanceType_elastic
  roles:
    - elasticsearch


- hosts: tag_MinionLabInstanceType_zookeeper
  roles:
    - zookeeper

- hosts: tag_MinionLabInstanceType_kafka
  roles:
    - kafka

- hosts: tag_MinionLabInstanceType_postgres
  roles:
    - postgres

- hosts: tag_MinionLabInstanceType_opennms
  roles:
    - opennms

- hosts: tag_MinionLabInstanceType_minion
  roles:
    - minion

- hosts: tag_MinionLabInstanceType_loadgen
  roles:
    - load-generator

- hosts: tag_MinionLabInstanceType_loadbalancer
  roles:
    - load-balancer
